name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      # Install necessary dependencies for building
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential make gcc libtool

      # Generate configure script if not already present
      - name: Generate configure script
        run: autoreconf -i

      # Make the configure script executable
      - name: Make configure script executable
        run: chmod +x ./configure

      # Run the configure script to configure the build environment
      - name: Run configure
        run: ./configure

      # Run make to compile the project
      - name: Run make
        run: make

      # Run make check to execute tests
      - name: Run make check
        run: make check

      # Run make distcheck to check the distributability of the project
      - name: Run make distcheck
        run: make distcheck
