jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Checkout the code from the repository

      # Install autoconf and automake tools
      - name: Install Autotools (autoconf, automake)
        run: sudo apt-get update && sudo apt-get install -y autoconf automake

      # Generate the configure script if it's missing
      - name: Generate configure script
        run: autoreconf -i  # This will generate the configure script from configure.ac

      # Make sure the configure script is executable
      - name: Make configure script executable
        run: chmod +x ./configure

      # Run the configure script to configure the build
      - name: Run configure
        run: ./configure

      # Run make to build the project
      - name: Run make
        run: make

      # Run tests using make check
      - name: Run make check
        run: make check

      # Run distcheck to check the package for distribution
      - name: Run make distcheck
        run: make distcheck
